export const assets = {
    'background': 'assets/export/background.png',
    'curtain': 'assets/export/curtain.png',
    // -------------------------------------------------------------------------
    'click': 'assets/export/click.png',
    'select': 'assets/export/select.png',
    // -------------------------------------------------------------------------
    'cancel': 'assets/export/cancel.png',
    'pass': 'assets/export/pass.png',
    'jump': 'assets/export/jump.png',    
    // -------------------------------------------------------------------------
    'tile': 'assets/export/tile.png',
    'tile-crack': 'assets/export/tile-crack.png',
    'crack-tile': 'assets/export/crack-tile.png', // EYE
    'tile-grass': 'assets/export/tile-grass.png',
    // -------------------------------------------------------------------------    
    'portal-red': 'assets/export/portal-red.png',
    'portal-blue': 'assets/export/portal-blue.png',
    'ninja-spawn': 'assets/export/ninja-spawn.png',
    'ninja-red': 'assets/export/ninja-red.png',
    'ninja-blue': 'assets/export/ninja-blue.png',
    'push': 'assets/export/push.png',
    'explode': 'assets/export/explode.png',
    'swap': 'assets/export/swap.png',
    'hooker-spawn': 'assets/export/hooker-spawn.png',    
    'hooker-red': 'assets/export/hooker-red.png',
    'hooker-blue': 'assets/export/hooker-blue.png',
    'pull': 'assets/export/pull.png',
    'pull-tile': 'assets/export/pull-tile.png',
    'cowboy-spawn': 'assets/export/cowboy-spawn.png',
    'cowboy-red': 'assets/export/cowboy-red.png',
    'cowboy-blue': 'assets/export/cowboy-blue.png',
    'mech-spawn': 'assets/export/mech-spawn.png',
    'mech-red': 'assets/export/mech-red.png',
    'mech-blue': 'assets/export/mech-blue.png',

    'druid-spawn': 'assets/export/druid-spawn.png',
    'druid-red': 'assets/export/druid-red.png',
    'druid-blue': 'assets/export/druid-blue.png',
    'grass-tile': 'assets/export/grass-tile.png',
    'destroy-grass': 'assets/export/destroy-grass.png',
    
    'brute-spawn': 'assets/export/brute-spawn.png',
    'brute-red': 'assets/export/brute-red.png',
    'brute-blue': 'assets/export/brute-blue.png',
    'sumoist-spawn': 'assets/export/sumoist-spawn.png',
    'sumoist-red': 'assets/export/sumoist-red.png',
    'sumoist-blue': 'assets/export/sumoist-blue.png',
    
    'smash': 'assets/export/smash.png',
    'throw': 'assets/export/throw.png',
    'shoot': 'assets/export/shoot.png',
    'rookshoot': 'assets/export/rookshoot.png',
    'sumojump': 'assets/export/sumojump.png',    
    'destroy-tile': 'assets/export/destroy-tile.png',        
};
